#sudo chown -R diego:diego /media/
version: "3.4"
services:
  vpn:
    image: qmcgaw/gluetun
    container_name: vpn
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=nordvpn
      - OPENVPN_USER=${VPN_USER}
      - OPENVPN_PASSWORD=${VPN_PASSWORD}
      - SERVER_COUNTRIES=France
    ports:
    # qbittorrent first instance ports 
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    # qbittorrent second instance ports
      - 8081:8081
      - 6882:6882
      - 6882:6882/udp
    # jackett ports
      - 9117:9117
    # flaresolverr ports
      - 8191:8191
    # deluge ports
      - 8112:8112 # port for deluge web UI to be reachable from local network
  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
      # - UMASK=022
      # - WEBUI_PORT=8090
    volumes:
      # - /media:/media
      - ${ROOT}/config/qbittorrent:/config # config files
      # - ${ROOT}/downloads:/downloads # downloads folder
      - ${ROOT}/downloads:/media/downloads # downloads folder
    network_mode: service:vpn # run on the vpn network
    restart: always
    depends_on:
      - vpn
    
  qbittorrent-dgo:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent-dgo
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
      - WEBUI_PORT=8081
      - TORRENTING_PORT=6882
    volumes:
      - ${ROOT}/config/qbittorrent-dgo:/config # config files
      - /media/diego/downloads:/media/diego/downloads # downloads folder
    network_mode: service:vpn # run on the vpn network
    restart: always
    depends_on:
      - vpn

  flaresolverr: 
    image: ghcr.io/flaresolverr/flaresolverr:pr-1282
    container_name: flaresolverr 
    # hostname: vpn 
    network_mode: service:vpn # run on the vpn network
    environment: 
      - LOG_LEVEL=${LOG_LEVEL:-info}  
      - LOG_HTML=${LOG_HTML:-false} 
      # - CAPTCHA_SOLVER=harvester
      - TZ=${TZ} # timezone, defined in .env
    restart: always

  jackett:
    container_name: jackett
    image: linuxserver/jackett:latest
    restart: always
    network_mode: service:vpn # run on the vpn network
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      # - ${ROOT}/downloads/torrent-blackhole:/downloads # place where to put .torrent files for manual download
      - ${ROOT}/config/jackett:/config # config files
    depends_on:
      - vpn
      - flaresolverr
  


  plex-server:
    container_name: plex-server
    image: plexinc/pms-docker:latest
    restart: always
    environment:
      - TZ=${TZ} # timezone, defined in .env
    network_mode: host
    volumes:
      - ${ROOT}/config/plex/db:/config # plex database
      - ${ROOT}/config/plex/transcode:/transcode # temp transcoded files
      # - ${ROOT}/complete:/data # media library
      - ${ROOT}:/media # media library
      # - ${ROOT}/downloads:/data
  
  sonarr: # https://downforeveryoneorjustme.com/skyhook.sonarr.tv
    container_name: sonarr
    image: linuxserver/sonarr:latest
    restart: always
    network_mode: host
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ROOT}/config/sonarr:/config # config files
      - ${ROOT}:/media

      # - ${ROOT}/complete/tv:/tv # tv shows folder 
      # - ${ROOT}/complete/docu:/docu # movies folder
      # - ${ROOT}/downloads:/downloads # download folder
    depends_on:
      - jackett

  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    restart: always
    network_mode: host
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ROOT}/config/radarr:/config # config files
      - ${ROOT}:/media
      # - ${ROOT}/complete/movies:/movies # movies folder
      # - ${ROOT}/complete/docu:/docu # movies folder
      # - ${ROOT}/downloads:/downloads # download folder
    depends_on:
      - jackett

  
  overseerr:
    image: linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - ${ROOT}/config/overseerr:/config
      # - ${ROOT}/movies:/movies
      # - ${ROOT}/tvshows:/tvshows
    ports:
      - 5055:5055
    restart: always
    network_mode: host
    depends_on:
      - sonarr
      - radarr
      - plex-server

  radarr-dgo:
    container_name: radarr-dgo
    image: linuxserver/radarr:latest
    restart: always
    # network_mode: host
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ROOT}/config/radarr-dgo:/config # config files
      - ${ROOT}:/media
      # - ${ROOT}/diego/config/radarr:/config # config files
      # - ${ROOT}/diego/complete/movies:/movies # movies folder
      # - ${ROOT}/diego/downloads:/downloads # download folder
    ports:
      - 7879:7878
    depends_on:
      - jackett

  # scrutiny:
  #   image: ghcr.io/analogj/scrutiny:master-omnibus
  #   container_name: scrutiny
  #   cap_add:
  #     - SYS_RAWIO
  #     - SYS_ADMIN #optional
  #   environment:
  #     - PUID=${PUID} # default user id, defined in .env
  #     - PGID=${PGID} # default group id, defined in .env
  #     - TZ=${TZ} # timezone, defined in .env
  #     - SCRUTINY_WEB=true
  #   volumes:
  #     - /media/config:/config
  #     - /run/udev:/run/udev:ro
  #     - /media/config/influxdb:/opt/scrutiny/influxdb
  #   ports:
  #     - 8082:8080
  #   devices:
  #     - "/dev/sdc"
  #     - "/dev/sdd"
  #     - "/dev/sde"
  #   restart: unless-stopped

  # deluge:
  #   container_name: deluge
  #   image: linuxserver/deluge:latest
  #   restart: always
  #   network_mode: service:vpn # run on the vpn network
  #   environment:
  #     - PUID=${PUID} # default user id, defined in .env
  #     - PGID=${PGID} # default group id, defined in .env
  #     - TZ=${TZ} # timezone, defined in .env
  #   volumes:
  #     - ${ROOT}/diego/downloads:/downloads # downloads folder
  #     - ${ROOT}/config/deluge:/config # config files

  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - ${ROOT}/config/tautulli:/config # config files
    ports:
      - 8181:8181
    restart: unless-stopped


  # plex-meta-manager:
  #   image: lscr.io/linuxserver/plex-meta-manager:latest
  #   container_name: plex-meta-manager
  #   environment:
  #     - PUID=${PUID} # default user id, defined in .env
  #     - PGID=${PGID} # default group id, defined in .env
  #     - TZ=${TZ} # timezone, defined in .env
  #     - PMM_TIME=03:00 #optional
  #     - PMM_RUN=False #optional
  #     - PMM_TEST=False #optional
  #     - PMM_NO_MISSING=False #optional
  #   # ports:
  #   #   - 8181:8181
  #   volumes:
  #     - ${ROOT}/config/plex-meta-manager/config:/config
  #   restart: unless-stopped


  # bazarr:
  #   container_name: bazarr
  #   image: linuxserver/bazarr
  #   restart: always
  #   network_mode: host
  #   environment:
  #     - PUID=${PUID} # default user id, defined in .env
  #     - PGID=${PGID} # default group id, defined in .env
  #     - TZ=${TZ} # timezone, defined in .env
  #     - UMASK_SET=022 #optional
  #   volumes:
  #     - ${ROOT}/config/bazarr:/config # config files
  #     - ${ROOT}/diego/complete/movies:/movies # movies folder
  #     - ${ROOT}/complete/movies:/tv # movies folder
  #     #- ${ROOT}/diego/complete/tv:/tv # tv shows folder
  #   ports:
  #     - 6767:6767
